FROM fluent/fluentd:edge-debian

USER root

# Install required OS deps
RUN apt-get update && apt-get install -y \
    build-essential \
    ruby-dev \
    libcurl4-openssl-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Fluentd plugins
RUN gem install \
    fluent-plugin-elasticsearch \
    fluent-plugin-prometheus \
    fluent-plugin-rewrite-tag-filter \
    --no-document

USER fluent